import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>I Like Farts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <iframe
          className={styles.video}
          src="https://www.youtube.com/embed/Z7NzSHDSJg8"
          title="YouTube video player"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        ></iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://nick.tobol.ski"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by tobo FARTS
        </a>
      </footer>
    </div>
  );
}
